name: buenro

networks:
  network:
    driver: bridge

services:
  mongo:
    image: mongo
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    networks:
      - network
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
  mongo-configdb:
